### ISSUE TITLE
Wrap R/shiftplot in to function

### ISSUE THREAD

**Issue by jwildfire** [SafetyGraphics/safetyCharts#1]

**Comment by bzkrouse** [comment]
Lines 109 and down attempt to surround the plot with boxplots like the interactive figure. I think we could remove this code for now.

**Comment by isaaczhao-alk** [comment]
Simplified lines 109 down to just one line using ggExtra, however boxplots are missing mean point
![image](https://user-images.githubusercontent.com/62663896/81103726-74ffe500-8edf-11ea-8f9b-6c1caabda37b.png)

**Comment by isaaczhao23** [comment]
adding link 

[https://github.com/SafetyGraphics/safetyCharts/blob/IZ_dev/R/safety_shift_plot.R](url)
