### ISSUE TITLE
Add crosstalk support?

### ISSUE THREAD

**Issue by pburnsdata** [SafetyGraphics/safetyCharts#113]
I wanted to add a filter control to an rmd to filter safety outlier explorer and immediately thought of using crosstalk. Not sure how much of a demand there is for this, but we could potentially add support for crosstalk at some point?https://rstudio.github.io/crosstalk/authoring.html

**Comment by pburnsdata** [comment]
although we can simply add filters via the js config....

**Comment by jwildfire** [comment]
Yeah, you almost definitely want to add chart-specific filters via the chart config (and pass that through to js). 

I do think there's a use case for crosstalk (or maybe custom event triggers) - here's an ancient safetyGraphics issue that touches on that: https://github.com/SafetyGraphics/safetyGraphics/issues/339

Going to close this one. Feel free to add comments on the issue above if you want to pursue this further.
