### ISSUE TITLE
Support blinded treatment in Adverse Event Explorer

### ISSUE THREAD

**Issue by pburnsdata** [SafetyGraphics/safetyCharts#114]
Currently [init_aeExplorer.R](https://github.com/SafetyGraphics/safetyCharts/blob/dev/R/init_aeExplorer.R) requires treatment_col from dm. However, I feel like adverse event explorer should support situations without treatment information (e.g. blinded data). While comparing treatments is a natural use case, it seems limiting to use treatment_col. 

qt-explorer implemented a similar improvement: https://github.com/SafetyGraphics/qtexplorer/pull/18

**Comment by jwildfire** [comment]
Yeah, you can definitely run the js chart without any treatment groups (though I confess I forget the exact params). I'd be happy to review a PR to the init function that would make the group column optional. Something like: 

```
if(is.null(treatment_col)) { 
    # Update settings here      
}
```

**Comment by pburnsdata** [comment]
@jwildfire saweet - ill make a pr

**Comment by pburnsdata** [comment]
Soo @jwildfire when it [combines settings with the defaults](https://github.com/RhoInc/aeexplorer/blob/4ff6a1e099576fd126eaeb4a4232977c9cd3c8e9/src/chart/util/setDefaults.js#L20), aeExplorer always seems to prioritize the "ARM" default setting unless you've got another column. Because `"" || "ARM and null || ARM` both resolve to "ARM". I know we have the None option in the group options dropdown that shows that the aeexplorer works without a group, but I'm not sure how to get pass the aggressive default setting of "ARM". @samussiah @nandriychuk do either of you remember setting up an aeexplorer without a group? 

An alternative option to allowing aeExplorer without a group specification would be to change init_aeExplorer.R to use  group_col setting instead of treatment_col like in [qtexplorer](https://github.com/SafetyGraphics/qtexplorer/pull/18). this would still require a group column but not necessarily treatment arm. Or even update aeexplorer if this seems like a use case that would come up again for others

**Comment by jwildfire** [comment]
Possible hack: 
``` 
if(variable.group == NULL){
   data.aes %>% mutate(group_placeholder="all pt")
   settings.defaults.groupCols = false
   settings.variables.group= "group_placeholder"
}
```

**Comment by pburnsdata** [comment]
@jwildfire @samussiah Thank you both!!! I'm glad I asked. PR here: https://github.com/SafetyGraphics/safetyCharts/pull/115 It's pretty similar to what you described Jeremy
