### ISSUE TITLE
Changing color of Safety Outlier Plot

### ISSUE THREAD

**Issue by rshinytools** [SafetyGraphics/safetyCharts#128]
Is their a guide or manual which provide details on changing the color of the safety outlier plot in R Shiny. Currently not able to figure out but it would be really helpful to have some guide in case user wants to change the theme of the plot.

**Comment by jwildfire** [comment]
Hi @rshinytools - thanks for the question.

The best reference for customizing charts are the safetyGraphics vignettes.  Unfortunately our current focus is on custom data mappings, so there isn't an easy way to customize color (or other chart appearance properties) in the safetyGraphics shiny app right now. 

It is theoretically possible to do this by editing the source code, but it's not super easy. The outlier plot is an htmlwidget that uses this [javascript library](https://github.com/RhoInc/safety-outlier-explorer). Color is configurable in the js version of the chart, but again, it isn't surfaced in safetyGraphics.

We do have wrappers in this package that allow additional customization for some of the charts (see `?hepExplorer` or `?aeExplorer`) and would let you change the colors, but we haven't added one in for the outlier chart yet. That would be fairly straightforward for us to add if it would be helpful for your use case.
