### ISSUE TITLE
Possible typos in aeExplorer_init()

### ISSUE THREAD

**Issue by xni7** [SafetyGraphics/safetyCharts#39]
@jwildfire , is this supposed to be `settings<-c(settings$aes, `**`settings$dm`**`) ` on [Line 11](https://github.com/SafetyGraphics/safetyCharts/blob/97330ab7ae59e7adda9147a9e57d52a3d0242bdb/inst/config/workflow/aeExplorer_init.R#L11)?

https://github.com/SafetyGraphics/safetyCharts/blob/97330ab7ae59e7adda9147a9e57d52a3d0242bdb/inst/config/workflow/aeExplorer_init.R#L11

And the text_key here is **`treatment_col`** instead of `trt_col` on [Line 16](https://github.com/SafetyGraphics/safetyCharts/blob/97330ab7ae59e7adda9147a9e57d52a3d0242bdb/inst/config/workflow/aeExplorer_init.R#L16)?
https://github.com/SafetyGraphics/safetyCharts/blob/97330ab7ae59e7adda9147a9e57d52a3d0242bdb/inst/config/workflow/aeExplorer_init.R#L16

**Comment by jwildfire** [comment]
Yep - those look like bugs to me. Kind of surprised the chart was working with these typos ... Will work on a fix now.

**Comment by jwildfire** [comment]
This was definitely broken. Basically no custom mapping was being passed through 😬
