### ISSUE TITLE
move /examples to roxygen headers

### ISSUE THREAD

**Issue by jwildfire** [SafetyGraphics/safetyCharts#5]
Hopefully this is mostly copy/paste from the `\examples` folder to the scripts in `\R` though I'm wondering if it might be worth simplifying the examples a bit in some cases. Histogram is fairly concise, but the other 2 examples are dozens of lines of code ... a bit long for roxygen style examples. 

Another option would be to convert the `\examples` folder in to a basic vignette, that way we could provide some additional context and show the images after the code. 

@bzkrouse @xni7 @ngbb @LJZeng Any strong opinions?

**Comment by xni7** [comment]
@jwildfire personally I feel it's important to have a reprex for each function, as in Hadley's book "@examples provides executable R code showing how to use the function in practice. This is a very important part of the documentation because **many people look at the examples first.**" In addition, it would be great to have a vignette that pieces different examples together as a coherent tutorial.

**Comment by LJZeng** [comment]
@

> Hopefully this is mostly copy/paste from the `\examples` folder to the scripts in `\R` though I'm wondering if it might be worth simplifying the examples a bit in some cases. Histogram is fairly concise, but the other 2 examples are dozens of lines of code ... a bit long for roxygen style examples.
> 
> Another option would be to convert the `\examples` folder in to a basic vignette, that way we could provide some additional context and show the images after the code.
> 
> @bzkrouse @xni7 @ngbb @LJZeng Any strong opinions?

@jwildfire I agree with this notion. I think there are multiple steps and suggest the following
* we consolidate the examples in a common subdirectory, and preserve it as `examples`. These examples will serve 1) be ready-made scripts for users who cone the repository can adapt to their datasets and 2) can be integrated into the vignette and documentation, while disrupting the file organization in the main directory keeping all functions for the repository. As such for a first step I will push a dev branch with simplified examples code this week for your review.

@xni7 I agree and think this is mutually exclusive to the examples subfolder. We in general should better document the main source code and ROxygen is fine. As a second step I will add ROxygen commentary to all main functions, and will discuss with @ngbb before undertaking this.

Lastly we will be able to generate he vignette more easily after this round of code consolidation and code-level documentation is complete, and prioritize documentation.

**Comment by jwildfire** [comment]
Agree with this. Set up a first example [here](https://github.com/SafetyGraphics/safetyCharts/blob/dev/R/tplyr_demog_chart.R). Going to close the issue since this is more of a general guidance for all charts moving forward than a specific task.
