### ISSUE TITLE
Create function to flatten lab data for nep-explorer

### ISSUE THREAD

**Issue by jwildfire** [SafetyGraphics/safetyCharts#6]
@samussiah to provide spec and link to equivalent js code in nep-explorer

**Comment by jwildfire** [comment]
May also want to use this for `hep-explorer` data prep down the road

**Comment by samussiah** [comment]
[Here's the code](https://github.com/SafetyGraphics/nep-explorer/blob/master/src/init/defineParticipantLevelData.js) that creates a one-record-per-participant data array.  These records drive the KDIGO scatter plot.

![image](https://user-images.githubusercontent.com/5428548/77353537-85854300-6d17-11ea-89e9-238fbcbc544e.png)

Within each participant array is a one-record-per-measure data array:

![image](https://user-images.githubusercontent.com/5428548/77353757-f167ab80-6d17-11ea-9135-765c4bb6ccee.png)

Subsets of these measures drive the participant-level time series plots.

**Comment by jwildfire** [comment]
The details here are definitely going to be a bit different to the approach we use in JS - mostly because we're using some nesting in js that I think we can avoid here. Some quick thoughts regarding the approach to the R code. 

- I think we want a function called something like `nepFlattenData` that starts with a long data (1 rec per person/visit/test) data.frame and outputs a wide dataset (just 1 rec per person). 
- For each measure, each person (so each row of the data set) should have columns for  `{measure}_fchange` (fold change), `{measure}_pchange` (percent change) and `{measure}_rawchange`. (@samussiah  can you confirm those are the needed measures for the chart).
- the function will eventually need to take 2 inputs `data` (for the long data.frame) and `settings` for the settings object that specifies the column mappings. It's fine to ignore the `settings` in the first draft, and just choose a single data.frame as a prototype. Once we've got that working we can use the guidance in the [custom workflow safetyGraphics vignette](https://cran.r-project.org/web/packages/safetyGraphics/vignettes/customWorkflows.html) to generalize. 
- I suggest ignoring the nested `values` object in @samussiah's notes for now (we can write a separate function that derives that information later)

Eventually, we'll probably want to generalize this function to a more flexible `flattenLabData()` function that will work with other data domains (like `hep-explorer`), but we can deal with that later as well.

**Comment by sripavanv** [comment]
Thank you Jeremy for the details. I will start on those lines and let you and team know as I go along.

**Comment by samussiah** [comment]
> * For each measure, each person (so each row of the data set) should have columns for  `{measure}_fchange` (fold change), `{measure}_pchange` (percent change) and `{measure}_rawchange`. (@samussiah  can you confirm those are the needed measures for the chart).

Right, for the KDIGO scatter plot we need change from baseline, fold change from baseline, and percent change from baseline for creatinine, cystatin C, eGFR (creatinine), and eGFR (cystatin C).

- prefixes
  - _creat_ for creatinine
  - _cystatc_ for cystatin C
  - _egfr_creat_ for eGFR (creatinine)
  - _egfr_cystatc_ for eGFR (cystatin C)
- suffixes
  - _chg_ for change from baseline
  - _fchg_ for fold change from baseline
  - _pchg_ for percent change from baseline (although we're probably okay with just fold change)

So eGFR (creatinine) percent change from baseline would be named _egfr_creat_pchg_.  Does that all sound okay?

**Comment by sripavanv** [comment]
@ spencer. Thanks for the details and the data. I have a few questions. 
1) what is the difference between fold change and raw change ? The formula for change from baseline is (Value-Baseline)/Baseline. May I know what is the formula for Fold change ? 
2) Should i subset the data manipulation to Creatnine, Cystatin C , eGFR and eGFRcys.
Thanks
Pavan

**Comment by samussiah** [comment]
Sure thing @sripavanv!  I was wondering the same thing and followed [Wikipedia's definition of fold change](https://en.wikipedia.org/wiki/Fold_change): `post-baseline/baseline`.  Then for absolute change from baseline you've got `post-baseline - baseline` and for percent change from baseline you've got `(post-baseline/baseline - 1)*100`.

As for the subset, you're right, the KDIGO scatter plot only needs creatinine, eGFR (creatinine), cystatin C, and eGFR (cystatin C).  Creatinine/cystatin C are the x-axis variables and and eGFR/eGFRcys are the y-axis variables.

**Comment by samussiah** [comment]
On the same note, we're actually looking for the maximal change within 7 days, so the baseline visit won't necessarily be the comparison visit.  As I understand it if we have this sequence of events:

|day|result|change from -3 days|change from -6 days|
|---|------|-------------------|-------------------|
| 1|100|  |  |
| 4|110|10|  |
| 7|115| 5|15|
|10|130|15|20|
|13|125|-5|10|

The maximal change would be 20, between days 4 (110) and 10 (130).  Unfortunately our simulated dataset doesn't have timepoints that close together so we can just look at maximal change between any two timepoints, instead of change from baseline.  I'm kind of explaining this to myself so let me know if anything sounds off.

**Comment by sripavanv** [comment]
Thanks Spencer. for the details and examples.

**Comment by sripavanv** [comment]
@Jeremy,  @Spencer, I have pushed a partial version of the function. Right now, it can calculate BASELINE, CHG, PCHG, FCHG. I will make an update and should push again next week or so which should be a more complete version that will also calculate the maximal change and   transpose the parameters. 
Regards
Pavan

**Comment by jwildfire** [comment]
Closing out the nep-explorer related issues for now, but can revisit as we re-start the development in that area.
